src/main/java/hu/webalapu/webshop/entities/OrderItem.java
package hu.webalapu.webshop.entities;

import javax.persistence.*;
import java.util.ArrayList;
import java.util.List;

/**
 * Created by herperger on 4/29/17.
 */
@Entity
public class OrderItem extends BaseEntity {

    @ManyToMany(fetch = FetchType.EAGER)
    private List<ProductInstance> productInstances = new ArrayList<>();

    @ManyToOne
    private ProductOrder order;

    @ManyToOne
    private Product product;

    public Product getProduct() {
        return product;
    }

    public void setProduct(Product product) {
        this.product = product;
    }

    public int getQuantity() {
        return productInstances.size();
    }

    public OrderItem(ProductOrder order) {
        this.order = order;
    }

    public OrderItem() {
    }

    public void addProductInstance(ProductInstance productInstance) {
        this.productInstances.add(productInstance);
    }

    public ProductOrder getOrder() {
        return order;
    }

    public void setOrder(ProductOrder order) {
        this.order = order;
    }

    public int calculateTotal() {
        int total = 0;

        for (ProductInstance productInstance :
                productInstances) {
            total += productInstance.getProduct().getPrice();
        }

        return total;
    }
}

src/main/java/hu/webalapu/webshop/controllers/Customer/CartManagedBean.java
package hu.webalapu.webshop.controllers.Customer;

import hu.webalapu.webshop.entities.CartItem;
import hu.webalapu.webshop.entities.Product;
import hu.webalapu.webshop.entities.ProductOrder;
import hu.webalapu.webshop.entities.WebShopUser;
import hu.webalapu.webshop.services.OrderService;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.servlet.http.HttpServletRequest;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

/**
 * Created by hory9 on 2017.05.13..
 */
@ManagedBean(name = "cart")
@SessionScoped
public class CartManagedBean {

    @Inject
    private OrderService orderService;

    @ManagedProperty(value = "#{confirmOrder}")
    private ConfirmOrderManagedBean confirmOrder;

    private List<CartItem> cartItems = new ArrayList<>();

    public void addProduct(Product product) {
        Optional<CartItem> optional = cartItems.stream().filter(cartItem -> cartItem.getProduct() == product).findAny();
        if(optional.isPresent()) {
            CartItem found = optional.get();
            found.increaseQuantity();
        } else {
            this.cartItems.add(new CartItem(product));
        }
    }

    public List<CartItem> getCartItems() {
        return cartItems;
    }

    public String confirmOrder() {
        ProductOrder newOrder = orderService.makeOrder(cartItems, null);
        cartItems.clear();
        if(newOrder != null) {
            confirmOrder.setLastOrder(newOrder);

            return "/faces/guest/confirmGuestOrder?faces-redirect=true";
        } else {
            return "";
        }
    }

    public String confirmCustomerOrder(WebShopUser user) {
        ProductOrder newOrder = orderService.makeOrder(cartItems, user);
        cartItems.clear();
        if(newOrder != null) {
            confirmOrder.setLastOrder(newOrder);

            return "/faces/guest/confirmCustomerOrder?faces-redirect=true";
        } else {
            return "";
        }
    }

    public ConfirmOrderManagedBean getConfirmOrder() {
        return confirmOrder;
    }

    public void setConfirmOrder(ConfirmOrderManagedBean confirmOrder) {
        this.confirmOrder = confirmOrder;
    }
}

src/main/java/hu/webalapu/webshop/controllers/Customer/ConfirmOrderManagedBean.java
package hu.webalapu.webshop.controllers.Customer;

import hu.webalapu.webshop.entities.ProductOrder;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpServletRequest;

/**
 * Created by herperger on 5/14/17.
 */
@ManagedBean(name = "confirmOrder")
@SessionScoped
public class ConfirmOrderManagedBean {
    private ProductOrder lastOrder;

    public String getOrderLink() {

        HttpServletRequest request = (HttpServletRequest) FacesContext.getCurrentInstance().getExternalContext().getRequest();
        String url = request.getRequestURL().toString();
        String baseURL = url.substring(0, url.length() - request.getRequestURI().length()) + request.getContextPath() + "/";

        return baseURL + "faces/guest/viewGuestOrder.xhtml?orderIdentifier=" + lastOrder.getIdentifier();
    }

    public void setLastOrder(ProductOrder lastOrder) {
        this.lastOrder = lastOrder;
    }
}

src/main/java/hu/webalapu/webshop/controllers/Customer/CustomerCartManagedBean.java
package hu.webalapu.webshop.controllers.Customer;

import hu.webalapu.webshop.authorization.UserProvider;
import hu.webalapu.webshop.entities.CartItem;
import hu.webalapu.webshop.entities.Product;
import hu.webalapu.webshop.entities.ProductOrder;
import hu.webalapu.webshop.entities.WebShopUser;
import hu.webalapu.webshop.services.OrderService;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.SessionScoped;
import javax.inject.Inject;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

/**
 * Created by herperger on 5/14/17.
 */
@ManagedBean(name = "customerCart")
@SessionScoped
public class CustomerCartManagedBean {
    @Inject
    private OrderService orderService;

    @ManagedProperty(value="#{userProvider}")
    private UserProvider userProvider;

    private List<CartItem> cartItems = new ArrayList<>();

    public void addProduct(Product product) {
        Optional<CartItem> optional = cartItems.stream().filter(cartItem -> cartItem.getProduct() == product).findAny();
        if(optional.isPresent()) {
            CartItem found = optional.get();
            found.increaseQuantity();
        } else {
            this.cartItems.add(new CartItem(product));
        }
    }

    public List<CartItem> getCartItems() {
        return cartItems;
    }

    public String confirmOrder() {
        ProductOrder newOrder = orderService.makeOrder(cartItems, userProvider.getCurrentUser());
        cartItems.clear();
        if(newOrder != null) {
            return "/faces/customer/customerOrders?faces-redirect=true";
        } else {
            return "";
        }
    }

    public UserProvider getUserProvider() {
        return userProvider;
    }

    public void setUserProvider(UserProvider userProvider) {
        this.userProvider = userProvider;
    }
}

src/main/java/hu/webalapu/webshop/controllers/Customer/CustomerOrdersManagedBean.java
package hu.webalapu.webshop.controllers.Customer;

import hu.webalapu.webshop.authorization.UserProvider;
import hu.webalapu.webshop.entities.ProductOrder;
import hu.webalapu.webshop.repositories.OrderRepository;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.RequestScoped;
import javax.inject.Inject;
import java.util.List;

/**
 * Created by herperger on 5/14/17.
 */
@ManagedBean
@RequestScoped
public class CustomerOrdersManagedBean {
    @Inject
    private OrderRepository orderRepository;

    @ManagedProperty(value="#{userProvider}")
    private UserProvider userProvider;

    @ManagedProperty(value="#{viewCustomerOrder}")
    private ViewCustomerOrderBean viewCustomerOrderBean;

    public List<ProductOrder> getCustomerOrders() {
        return orderRepository.findByUser(userProvider.getCurrentUser());
    }

    public String viewProductOrder(ProductOrder productOrder) {
        viewCustomerOrderBean.setOrder(productOrder);

        return "/faces/customer/viewCustomerOrder?faces-redirect=true";
    }

    public UserProvider getUserProvider() {
        return userProvider;
    }

    public void setUserProvider(UserProvider userProvider) {
        this.userProvider = userProvider;
    }

    public ViewCustomerOrderBean getViewCustomerOrderBean() {
        return viewCustomerOrderBean;
    }

    public void setViewCustomerOrderBean(ViewCustomerOrderBean viewCustomerOrderBean) {
        this.viewCustomerOrderBean = viewCustomerOrderBean;
    }
}

src/main/java/hu/webalapu/webshop/controllers/Customer/ShopManagedBean.java
package hu.webalapu.webshop.controllers.Customer;

import hu.webalapu.webshop.entities.Product;
import hu.webalapu.webshop.entities.ProductCategory;
import hu.webalapu.webshop.repositories.BaseRepository;
import hu.webalapu.webshop.repositories.ProductCategoryRepository;
import hu.webalapu.webshop.repositories.ProductInstanceRepository;
import hu.webalapu.webshop.repositories.ProductRepository;
import hu.webalapu.webshop.util.EntitiesManagedBean;
import hu.webalapu.webshop.util.FilterableLazyModel;
import hu.webalapu.webshop.util.LazyEntityDataModel;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.inject.Inject;
import java.util.List;

/**
 * Created by herperger on 5/13/17.
 */
@ManagedBean(name = "shop")
@SessionScoped
public class ShopManagedBean extends EntitiesManagedBean<Product> {

    @Inject
    private ProductRepository productRepository;

    @Inject
    private ProductCategoryRepository productCategoryRepository;

    private ProductCategory selectedProductCategory;

    private FilterableLazyModel lazyModel;

    @PostConstruct
    public void init() {
        super.init(Product.class, productRepository);
    }

    @Override
    protected LazyEntityDataModel<Product> createLazyModel(BaseRepository<Product> entityRepository) {
        return new FilterableLazyModel<>(productRepository);
    }

    public List<ProductCategory> getProductCategories() {
        return productCategoryRepository.findAll();
    }

    public void setSelectProductCategory(ProductCategory productCategory) {
        ((FilterableLazyModel<Product>) getLazyModel()).addFilter("productCategory", productCategory);
    }

    public long getStockCount(Product product) {
        return productRepository.findStockCount(product);
    }

}

src/main/java/hu/webalapu/webshop/controllers/Customer/ViewCustomerOrderBean.java
package hu.webalapu.webshop.controllers.Customer;

import hu.webalapu.webshop.entities.ProductOrder;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

/**
 * Created by herperger on 5/14/17.
 */
@SessionScoped
@ManagedBean(name = "viewCustomerOrder")
public class ViewCustomerOrderBean {
    private ProductOrder order;

    public ProductOrder getOrder() {
        return order;
    }

    public void setOrder(ProductOrder order) {
        this.order = order;
    }
}

src/main/java/hu/webalapu/webshop/controllers/Customer/ViewOrderBean.java
package hu.webalapu.webshop.controllers.Customer;

import hu.webalapu.webshop.entities.ProductOrder;
import hu.webalapu.webshop.entities.WebShopUser;
import hu.webalapu.webshop.repositories.OrderRepository;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.RequestScoped;
import javax.faces.bean.SessionScoped;
import javax.inject.Inject;

/**
 * Created by herperger on 5/14/17.
 */
@ManagedBean
@RequestScoped
public class ViewOrderBean {
    @ManagedProperty(value = "#{param.orderIdentifier}")
    private String orderIdentifier;

    @Inject
    private OrderRepository orderRepository;

    public ProductOrder getOrder() {
        return orderRepository.findByIdentifier(orderIdentifier);
    }

    public String getOrderIdentifier() {
        return orderIdentifier;
    }

    public void setOrderIdentifier(String orderIdentifier) {
        this.orderIdentifier = orderIdentifier;
    }
}

src/main/webapp/faces/customer/cart.xhtml
<ui:composition template="/faces/customer/customerpage.xhtml"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui">
    <ui:define name="content">
        <h:form id="form">
            <p:dataList value="#{customerCart.cartItems}" var="cartItem">
                <f:facet name="header">
                    Kosárban lévő termékek
                </f:facet>
                #{cartItem.product.name}, #{cartItem.quantity}
            </p:dataList>

            <h:commandButton value="Rendelés elküldése" action="#{customerCart.confirmOrder()}">

            </h:commandButton>
        </h:form>

    </ui:define>
</ui:composition>

src/main/webapp/faces/customer/confirmCustomerOrder.xhtml
<ui:composition template="/faces/customer/customerpage.xhtml"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui">
    <ui:define name="content">
        <h:form id="form">
            <h:outputText value="Köszönjük megrendelését! Megrendelésének státuszát nyomon követketi a következő linken: ">

            </h:outputText>

            <h:outputLink value="${confirmOrder.orderLink}">
                ${confirmOrder.orderLink}
            </h:outputLink>
        </h:form>

    </ui:define>
</ui:composition>

src/main/webapp/faces/customer/customerOrders.xhtml
<ui:composition template="/faces/customer/customerpage.xhtml"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui">
    <ui:define name="content">
        <h:form id="form">
            <p:dataList value="#{customerOrdersManagedBean.customerOrders}" var="order">
                <f:facet name="header">
                    Megrendelések
                </f:facet>
                <p:commandLink value="${order.identifier} - ${order.orderDate}"
                               action="#{customerOrdersManagedBean.viewProductOrder(order)}">
                </p:commandLink>
            </p:dataList>
        </h:form>

    </ui:define>
</ui:composition>

src/main/webapp/faces/customer/customerpage.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
<h:head>
    <title>
        <ui:insert name="title">

        </ui:insert>
    </title>
</h:head>
<h:body>
    <h:form>
        <p:growl id="messages"/>

        <p:menubar>
            <p:menuitem value="Rendelés" url="/faces/customer/shop.xhtml"/>
            <p:menuitem value="Kosár" url="/faces/customer/cart.xhtml"/>
            <p:menuitem value="Saját rendelések" url="/faces/customer/customerOrders.xhtml"/>
            <f:facet name="options">
                <p:commandButton value="Kijelentkezés" action = "#{admin.logout}" icon="ui-icon-extlink" />
            </f:facet>
        </p:menubar>
    </h:form>
    <div>
        <ui:insert name="content">

        </ui:insert>
    </div>
</h:body>

</html>

src/main/webapp/faces/customer/shop.xhtml
<ui:composition template="/faces/customer/customerpage.xhtml"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui">
    <ui:define name="content">

        <p:layout >
            <p:layoutUnit position="west" resizable="true" minSize="40">
                <h:form id="productCategoryForm">
                <p:dataList value="#{shop.productCategories}" var="productCategory">
                    <f:facet name="header">
                        Termék kategóriák
                    </f:facet>
                    <p:commandLink value="#{productCategory.name}" update=":productForm:products">
                        <f:setPropertyActionListener value="#{productCategory}" target="#{shop.selectProductCategory}" />
                    </p:commandLink>
                </p:dataList>
                </h:form>
            </p:layoutUnit>

            <p:layoutUnit position="center">

                <h:form id="productForm">
                    <p:dataGrid var="product" value="#{shop.lazyModel}" columns="3" layout="grid"
                                rows="12" paginator="true" id="products" lazy="true"
                                paginatorTemplate="{CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
                                rowsPerPageTemplate="6,12,16">

                        <f:facet name="header">
                            Termékek
                        </f:facet>

                        <p:panel header="#{product.name}" style="text-align:center">
                            <h:panelGrid columns="1" style="width:100%">
                                <img src="https://malnapc.hu/wp-content/uploads/2016/03/Raspberry_Pi_3.jpg" width="100" height="100">

                                </img>
                                <h:outputText value="Raktáron: ${shop.getStockCount(product)} db"></h:outputText>
                                <h:outputText value="${product.price} Ft"></h:outputText>

                                <p:commandLink value="Kosárba" actionListener="#{customerCart.addProduct(product)}">

                                </p:commandLink>
                            </h:panelGrid>
                        </p:panel>

                    </p:dataGrid>
                </h:form>

            </p:layoutUnit>
        </p:layout>

    </ui:define>
</ui:composition>

src/main/webapp/faces/customer/viewCustomerOrder.xhtml
<ui:composition template="/faces/customer/customerpage.xhtml"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui">
    <ui:define name="content">
        <h:form id="form">
            <p:dataList value="#{viewCustomerOrder.order.orderItems}" var="orderItem">
                <f:facet name="header">
                    Megrendelt termékek
                </f:facet>
                <h:outputText value="${orderItem.product.name} ${orderItem.quantity} db - ${orderItem.calculateTotal()} Ft">

                </h:outputText>
            </p:dataList>

            <h:outputText value="Végösszeg: ${viewCustomerOrder.order.calculateTotal()} Ft"></h:outputText>
        </h:form>

    </ui:define>
</ui:composition>