src/main/java/hu/webalapu/webshop/controllers/inventorymanagement/InventoryManagementManagedBean.java
package hu.webalapu.webshop.controllers.inventorymanagement;

import hu.webalapu.webshop.entities.Product;
import hu.webalapu.webshop.entities.ProductCategory;
import hu.webalapu.webshop.entities.ProductInstance;
import hu.webalapu.webshop.repositories.ProductCategoryRepository;
import hu.webalapu.webshop.repositories.ProductInstanceRepository;
import hu.webalapu.webshop.repositories.ProductRepository;
import hu.webalapu.webshop.util.EntitiesManagedBean;

import javax.annotation.PostConstruct;
import javax.faces.bean.ApplicationScoped;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.inject.Inject;
import java.util.List;

/**
 * Created by herperger on 5/1/17.
 */
@ManagedBean(name = "productInstances")
@SessionScoped
public class InventoryManagementManagedBean extends EntitiesManagedBean<ProductInstance> {
    @Inject
    private ProductInstanceRepository productInstanceRepository;

    @Inject
    private ProductRepository productRepository;

    @PostConstruct
    public void init() {
        super.init(ProductInstance.class, productInstanceRepository);
    }

    public List<Product> getProducts() {
        return productRepository.findAll();
    }


    @ManagedBean(name = "productConverter")
    @ApplicationScoped
    public static class ProductCategoryConverter implements Converter {

        @Inject
        private ProductRepository productRepository;

        @Override
        public Object getAsObject(FacesContext context, UIComponent component, String value) {
            return productRepository.findById(Long.parseLong(value));
        }

        @Override
        public String getAsString(FacesContext context, UIComponent component, Object value) {
            return ((Product)value).getId().toString();
        }
    }
}

src/main/webapp/faces/admin/inventorymanagement/inventorymanagement.xhtml
<ui:composition template="/faces/admin/adminpage.xhtml"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui">
    <ui:define name="content">
        <h:form id="form">
            <p:dataTable id="dataTable" var="productInstance" value="#{productInstances.lazyModel}" styleClass="userDataTableStyle"
                         paginator="true" rows="3" selection="#{productInstances.selectedEntities}"
                         paginatorTemplate="{CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
                         lazy="true" rowsPerPageTemplate="5, 10, 15">
                <f:facet name="header">
                    Raktárkészlet
                </f:facet>
                <p:column selectionMode="multiple" style="width:18px" />
                <p:column  sortBy="#{productInstance.product.name}">
                    <f:facet name="header">
                        <h:outputText value="Terméknév" />
                    </f:facet>
                    <p:commandLink value="#{productInstance.product.name}" update=":editProductInstanceForm:display" oncomplete="$('#editProductInstanceDialog').show()"  title="View">
                        <f:setPropertyActionListener value="#{productInstance}" target="#{productInstances.editedEntity}" />
                    </p:commandLink>
                </p:column>

                <p:column sortBy="#{productInstance.serialNumber}">
                    <f:facet name="header">
                        <h:outputText value="Sorozatszám" />
                    </f:facet>
                    <h:outputText value="#{productInstance.serialNumber}" />
                </p:column>

                <f:facet name="footer">
                    <p:commandButton value="Raktárkészlet növelése" update=":editProductInstanceForm:display" actionListener="#{productInstances.prepareNewEntity}" oncomplete="$('#editProductInstanceDialog').show()" icon="ui-icon-star"/>
                    <p:commandButton value="Raktáron lévő termékek törlése" actionListener="#{productInstances.doDeleteEntities}"
                                     update="dataTable" icon="ui-icon-trash"/>
                </f:facet>
            </p:dataTable>
        </h:form>


        <p:dialog header="Raktáron lévő termék szerkesztése" widgetVar="productInstanceDetailDlg" resizable="false" id="editProductInstanceDialog" >
            <h:form id="editProductInstanceForm">
                <p:panelGrid id="display" columns="2" cellpadding="4" style="margin:0 auto;">
                    <h:outputText value="Sorozatszám:"></h:outputText>
                    <h:inputText value="#{productInstances.editedEntity.serialNumber}"/>

                    <h:outputText value="Termék:"></h:outputText>
                    <p:selectOneMenu id="product" converter="#{productConverter}" value="#{productInstances.editedEntity.product}">
                        <f:selectItems value="${productInstances.products}" var="product" itemLabel="#{product.name}" itemValue="#{product}"/>
                    </p:selectOneMenu>

                    <f:facet name="footer">
                        <p:commandButton value="Mentés" update=":form:dataTable, :growl"
                                         oncomplete="handleSubmitRequest(xhr, status, args, 'productInstanceDetailDialog','editProductInstanceForm'); "
                                         actionListener="#{productInstances.doSaveEntity}"/>
                    </f:facet>
                </p:panelGrid>
            </h:form>
        </p:dialog>

        <p:growl id="growl" showDetail="true" life="100000" />

        <script type="text/javascript">
            function handleSubmitRequest(xhr, status, args, dialogName, formName) {
                dialog = jQuery('#'+dialogName);
                if(args.validationFailed) {
                    dialog.effect("shake", { times:3 }, 100);
                } else {
                    clearForm(formName);
                    $('#editProductInstanceDialog').hide();
                }
            }
            function clearForm(formName){
                jQuery('#'+formName).each(function(){
                    this.reset();
                });
            }
        </script>
    </ui:define>
</ui:composition>